Install zsh before installing oh-my-zsh

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -5,7 +5,18 @@ set -euo pipefail
 mkdir -p ~/.ssh
 mkdir -p ~/.bin
 
+if [ -x "$(command -v brew)" ]; then
+    brew install zsh
+elif [ -x "$(command -v apt)" ]; then
+    sudo apt install zsh
+else
+    echo "Cannot automatically install zsh, aborting..."
+    exit 1
+fi
+
 sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
+rm -f ~/.zshrc
+rm -f ~/.zshenv
 ln -s zshrc ~/.zshrc
 ln -s zshenv ~/.zshenv
 ln -s zsh/cloud-light.zsh-theme ~/.oh-my-zsh/themes/
